repos:
  - repo: local
    hooks:
      - id: custom ruff format
        name: ruff format & sort imports
        entry: bash -c 'ruff check --config pyproject.toml  --fix && ruff format --config pyproject.toml'
        language: python
        pass_filenames: false
        additional_dependencies: ["ruff"]
